// enums.ts
export enum CategoryEnum {
  POLITICS_AND_GOVERNANCE = "POLITICS_AND_GOVERNANCE",
  ECONOMY_AND_DEVELOPMENT = "ECONOMY_AND_DEVELOPMENT",
  LAW_AND_JUSTICE = "LAW_AND_JUSTICE",
  EDUCATION = "EDUCATION",
  ENVIRONMENT_AND_SUSTAINABILITY = "ENVIRONMENT_AND_SUSTAINABILITY",
  SOCIAL_ISSUES = "SOCIAL_ISSUES",
  HEALTH_AND_WELLNESS = "HEALTH_AND_WELLNESS",
  SCIENCE_AND_TECHNOLOGY = "SCIENCE_AND_TECHNOLOGY",
  ENTERTAINMENT_AND_MEDIA = "ENTERTAINMENT_AND_MEDIA",
  SPORTS_AND_LEISURE = "SPORTS_AND_LEISURE",
}

export enum InterestEnum {
  ELECTIONS = "ELECTIONS",
  POLITICAL_PARTIES = "POLITICAL_PARTIES",
  GOVERNMENT_POLICIES = "GOVERNMENT_POLICIES",
  CORRUPTION = "CORRUPTION",
  INTERNATIONAL_RELATIONS = "INTERNATIONAL_RELATIONS",
  EQUALITY = "EQUALITY",
  POVERTY = "POVERTY",
  HUMAN_RIGHTS = "HUMAN_RIGHTS",
}

export const CATEGORY_INTERESTS = {
  [CategoryEnum.POLITICS_AND_GOVERNANCE]: [
    InterestEnum.ELECTIONS,
    InterestEnum.POLITICAL_PARTIES,
    InterestEnum.GOVERNMENT_POLICIES,
    InterestEnum.CORRUPTION,
    InterestEnum.INTERNATIONAL_RELATIONS,
  ],
  [CategoryEnum.SOCIAL_ISSUES]: [
    InterestEnum.EQUALITY,
    InterestEnum.POVERTY,
    InterestEnum.HUMAN_RIGHTS,
  ],
  // Add more interests for other categories as needed
};

export const HOMOGENEOUS_CATEGORIES = [
  CategoryEnum.POLITICS_AND_GOVERNANCE,
  CategoryEnum.ECONOMY_AND_DEVELOPMENT,
  CategoryEnum.LAW_AND_JUSTICE,
  CategoryEnum.EDUCATION,
  CategoryEnum.ENVIRONMENT_AND_SUSTAINABILITY,
];

export const HETEROGENEOUS_CATEGORIES = [
  CategoryEnum.SOCIAL_ISSUES,
  CategoryEnum.HEALTH_AND_WELLNESS,
  CategoryEnum.SCIENCE_AND_TECHNOLOGY,
  CategoryEnum.ENTERTAINMENT_AND_MEDIA,
  CategoryEnum.SPORTS_AND_LEISURE,
];
